### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by JelleBouma** [joaquinlpereyra/twitterImgBot#13]
jelle@jelle-OptiPlex-GX620:~/twitterImgBot$ python twitterbot.py
Traceback (most recent call last):
  File "twitterbot.py", line 3, in <module>
    from settings import config
  File "/home/jelle/twitterImgBot/settings/config.py", line 2, in <module>
    import configparser
ImportError: No module named configparser

It seems like im missing a module?

**Comment by joaquinlpereyra** [comment]
Looks like a problem with your Python installation, configparser is in the standard python library: https://docs.python.org/3/library/configparser.html

Closing this bug, but feel free to ask for help anyway.

**Comment by JelleBouma** [comment]
Thank you, I'm using  the latest version of Ubuntu (32 bit) and haven't used Python before or modified my Python installation in any way whatsoever. I'll try to find a solution on google, if you have any thoughts that might be helpful too.

**Comment by JelleBouma** [comment]
i found out what was giving me trouble, in ubuntu both python 2.7 and python 3.5 are installed and i shouldve used python3 twitterbot.py to run the bot and pip3 install tweepy to install tweepy. its working now, thank you for your help!

**Comment by JelleBouma** [comment]
i cant get it to work with cron though, how did you achieve this?

**Comment by JelleBouma** [comment]
I got cron to work, just an error in the path. Thanks again.

**Comment by joaquinlpereyra** [comment]
Glad you solved this! :)

Please do not hesitate to report any other problem.
