### ISSUE TITLE
KeyError: 'Twitter' + 1 Other Issue

### ISSUE THREAD

**Issue by Puppydaze** [joaquinlpereyra/twitterImgBot#14]
Running into an error when I try to run the script.
I'm not very savvy in coding, so I'm not quite sure what it is exactly, but here's what it looks like:
![screenshot_143](https://cloud.githubusercontent.com/assets/11083026/21128249/376793d0-c0ae-11e6-8a91-717373d8a200.png)

If you could direct me in fixing this problem, I would be very gracious.

EDIT: Sometimes I run into this error instead:
![screenshot_144](https://cloud.githubusercontent.com/assets/11083026/21128482/334d281c-c0b0-11e6-93af-27a3cb17b149.png)

**Comment by Puppydaze** [comment]
Figured out the issue. It had to do with bash not recognizing the folder existed since it was created in Windows, not linux. Sorry for the inconvenience

**Comment by joaquinlpereyra** [comment]
Glad you solved it!
