### ISSUE TITLE
Images repeat before the amount of photos listed in settings

### ISSUE THREAD

**Issue by Puppydaze** [joaquinlpereyra/twitterImgBot#15]
I'm having an issue where images are repeating, even though the number of photos before repeat listed in the settings (200) has not been reached.

This is what my settings look like:
![screenshot_145](https://cloud.githubusercontent.com/assets/11083026/21204309/b031d1a0-c20b-11e6-9683-c2c54fe1509b.png)

Here is the log, where it repeats:
![screenshot_146](https://cloud.githubusercontent.com/assets/11083026/21204476/8a3e7056-c20c-11e6-8a1f-a2b7f4bd53e6.png)

Could it be because I don't have 200 pictures in my folder?
All I want is for it never to repeat images until all of them have been choosen already. I also add into the folder everyday, so I have to change the number of photos before repeat to something high.

Any help would be appreciated! Thank you.

**Comment by joaquinlpereyra** [comment]
Hi! I'm aware of this bug, but haven't had the time to research further into it. Please look into #12. If you're willing to provide a pull request I will gladly provide any help I can!
