### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by syphon5** [joaquinlpereyra/twitterImgBot#17]
Receive following error when running the twitterbot.py script. My setup is "Python 3.5.1 |Anaconda 4.0.0 (64-bit)|"

File "twitterbot.py", line 69
    media = random.choice(media_list)
        ^
SyntaxError: invalid syntax

**Comment by joaquinlpereyra** [comment]
I recently merged a pull request without testing in. My bad. The syntax error should be fixed now, try redowloading the file and let me know how this went.

**Comment by syphon5** [comment]
Boom. Sync'd and it works. Thanks!
