### ISSUE TITLE
Use parent folder name as text? 

### ISSUE THREAD

**Issue by AdrienLF** [joaquinlpereyra/twitterImgBot#18]
Hi, I'm just starting using your bot and so far, so good.

I have a folder with subfolders for each artist. As I want to credit the artist, I would like to tweet the name of the parent folder. Any idea how to do this?

**Comment by AdrienLF** [comment]
Found the solution thanks to a previous answer. On line 15 on bot/status.py, it should be:

`self.text = tweet_media.split(os.sep)[-2].title()`

**Comment by joaquinlpereyra** [comment]
@AdrienLF glad you found a suitable solution :)
